name: "pcc-admin-service-app"
services:
  app:
    platform: linux/amd64
    build: 
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}  # Pass to Dockerfile  
      dockerfile: Dockerfile
    stdin_open: true
