name: "pcc-admin-service-container"
services:
  server:
    platform: linux/amd64
    image: pcc-admin-service:v1.0.8
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    env_file:
      - .env
